require_relative "github"
require_relative "models/factory"

class Reviewer
  DEFAULT_PROMPT = <<~PROMPT
    You are an expert code reviewer. Review the following pull request diff and provide constructive feedback.

    Focus on:
    - Bugs or logic errors
    - Security vulnerabilities
    - Performance concerns
    - Code clarity and maintainability
    - Missing edge case handling

    Be concise. Use markdown formatting. If the code looks good, say so briefly.

    PR Diff:
    ```diff
    %<diff>s
    ```
  PROMPT

  def initialize(provider:, model:, api_key:, github_token:, repo:, pr_number:, custom_prompt: nil)
    @model = Models::Factory.build(provider: provider, model: model, api_key: api_key)
    @github = GitHub.new(token: github_token, repo: repo, pr_number: pr_number)
    @custom_prompt = custom_prompt
  end

  def run
    diff = @github.diff
    prompt = build_prompt(diff)
    review = @model.review(prompt)
    @github.post_comment(format_comment(review))
  end

  private

  def build_prompt(diff)
    if @custom_prompt && !@custom_prompt.empty?
      "#{@custom_prompt}\n\nPR Diff:\n```diff\n#{diff}\n```"
    else
      format(DEFAULT_PROMPT, diff: diff)
    end
  end

  def format_comment(review)
    "## AI Code Review\n\n#{review}\n\n---\n*Generated by [ai-pr-review-action](https://github.com/#{ENV['GITHUB_ACTION_REPOSITORY']})*"
  end
end
