use crate::{config::Config, github, models};
use anyhow::{Context, Result};
use std::env;
use tracing::info;

const DEFAULT_PROMPT: &str = "You are an expert code reviewer. Review the following pull request diff and provide constructive feedback.\n\nFocus on:\n- Bugs or logic errors\n- Security vulnerabilities\n- Performance concerns\n- Code clarity and maintainability\n- Missing edge case handling\n\nBe concise. Use markdown formatting. If the code looks good, say so briefly.";

/// Core review logic — usable from both Action mode and the MCP server.
pub async fn review_pr(config: &Config, repo: &str, pr_number: u64) -> Result<String> {
    let api_key = config
        .api_key()
        .with_context(|| format!("Missing API key for provider: {}", config.provider))?;

    info!(repo, pr_number, provider = %config.provider, model = %config.model, "Starting review");

    let client = github::Client::new(&config.github_token, repo, pr_number)?;
    let diff = client.diff().await?;

    let prompt = build_prompt(&diff, config.prompt.as_deref());
    let model = models::build(&config.provider, &config.model, api_key)?;
    model.review(&prompt).await
}

/// GitHub Actions entry point — reads env, reviews, posts comment.
pub async fn run(config: Config) -> Result<()> {
    let repo = env::var("GITHUB_REPOSITORY").context("Missing GITHUB_REPOSITORY")?;
    let github_ref = env::var("GITHUB_REF").context("Missing GITHUB_REF")?;
    let pr_number: u64 = github_ref
        .split('/')
        .nth(2)
        .and_then(|s| s.parse().ok())
        .context("Could not parse PR number from GITHUB_REF")?;

    let review = review_pr(&config, &repo, pr_number).await?;

    let client = github::Client::new(&config.github_token, &repo, pr_number)?;
    let action_repo = env::var("GITHUB_ACTION_REPOSITORY").unwrap_or_default();
    let comment = format!(
        "## AI Code Review\n\n{review}\n\n---\n*Generated by [ai-pr-review-action](https://github.com/{action_repo})*"
    );

    client.post_comment(&comment).await
}

fn build_prompt(diff: &str, custom: Option<&str>) -> String {
    let base = custom.unwrap_or(DEFAULT_PROMPT);
    format!("{base}\n\nPR Diff:\n```diff\n{diff}\n```")
}
